name: DevSecOps Trivy Scan

on:
  push:
    branches:
      - main

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.1_Linux-64bit.deb || true
          sudo dpkg -i trivy_*.deb || true
          sudo apt-get install -f -y

      - name: Run Trivy Scan
        run: |
          trivy image --severity HIGH,CRITICAL bkimminich/juice-shop
